/* --- Template Theme Configuration --- */
export interface TemplateTheme {
  id: string
  name: string
  // Background colors
  bgPrimary: string
  bgSecondary: string
  bgDoor: string
  bgDoorGradient: string
  // Accent / gold colors
  accent: string
  accentLight: string
  accentDark: string
  accentRgb: string // for rgba usage
  // Text colors
  textPrimary: string
  textSecondary: string
  textMuted: string
  // Border / ornamental
  borderAccent: string
  borderSubtle: string
  // Scratch card
  scratchBg: string[]
  scratchAccent: string
  // Firework colors
  fireworkColors: string[]
  // Confetti colors
  confettiColors: string[]
    // Video and Hero Media (For specific templates)
    openingVideoUrl?: string
    openingVideoPosterUrl?: string
    heroMediaUrl?: string
  // Door style configuration
  doorStyle: {
    type: 'classic-doors' | 'curtains' | 'petals' | 'split-screen' | 'archway' | 'scroll' | 'geometric' | 'lotus' | 'lantern' | 'dome'
    doorMaterial: 'wood' | 'lacquer' | 'glass' | 'stone' | 'painted'
    panelLayout: '2-panel' | '4-panel' | 'arched-panel' | 'glass-grid' | 'flat' | 'carved' | 'studded'
    handleType: 'ring-knocker' | 'lever' | 'pull' | 'iron-ring' | 'crystal' | 'none'
    frameStyle: 'ornate' | 'simple' | 'arched-stone' | 'painted-rosettes' | 'modern'
    leftText: string
    rightText: string
    leftTextLang: 'ar' | 'en' | 'ur'
    rightTextLang: 'ar' | 'en' | 'ur'
    svgPattern: 'arch' | 'geometric' | 'floral' | 'minimal' | 'mandala' | 'paisley' | 'diamond' | 'star' | 'lantern' | 'dome'
    centerIcon: string
    animationClass: string
    buttonStyle: 'circle' | 'diamond' | 'shield' | 'hexagon' | 'star'
  }
  fontDisplay?: string
  fontCalligraphy?: string
  isLight?: boolean
  isRoyal?: boolean
  getOpacityStyle: (type: 'text' | 'bg' | 'border' | 'accent', defaultOpacity: number) => string
}

export const TEMPLATE_THEMES: Record<string, Omit<TemplateTheme, 'getOpacityStyle'>> = {
  'lumina-celebration': {
    id: 'lumina-celebration',
    name: 'Lumina Celebration (Event)',
    isLight: false,
    bgPrimary: '#0f0518',
    bgSecondary: '#190a2a',
    bgDoor: '#0f0518',
    bgDoorGradient: 'linear-gradient(135deg, #190a2a 0%, #2a0845 50%, #0f0518 100%)',
    accent: '#00f0ff',
    accentLight: '#66f5ff',
    accentDark: '#008b99',
    accentRgb: '0,240,255',
    textPrimary: '#ffffff',
    textSecondary: '#e2d5f8',
    textMuted: '#a38db8',
    borderAccent: 'rgba(0,240,255,0.3)',
    borderSubtle: 'rgba(0,240,255,0.1)',
    scratchBg: ['#190a2a', '#2a0845', '#0f0518'],
    scratchAccent: '#00f0ff',
    fireworkColors: ['#ff007f', '#00f0ff', '#7000ff', '#ffb800', '#ffffff'],
    confettiColors: ['#ff007f', '#00f0ff', '#7000ff', '#ffb800', '#ffffff'],
    doorStyle: {
      type: 'split-screen',
      doorMaterial: 'glass',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'Lets',
      rightText: 'Party',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'minimal',
      centerIcon: '🎉',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-sans',
  },
  'emerald-noir': {
    id: 'emerald-noir',
    name: 'Emerald Noir',
    bgPrimary: '#0f1a16',
    bgSecondary: '#0a1210',
    bgDoor: '#152822',
    bgDoorGradient: 'linear-gradient(135deg, #152822 0%, #1f332c 50%, #141f1b 100%)',
    accent: '#d4a853',
    accentLight: '#e8c66a',
    accentDark: '#b4914d',
    accentRgb: '180,145,77',
    textPrimary: '#e0ccaa',
    textSecondary: '#c9a96e',
    textMuted: '#8f7c56',
    borderAccent: 'rgba(180,145,77,0.4)',
    borderSubtle: 'rgba(180,145,77,0.15)',
    scratchBg: ['#1a332a', '#0f2920', '#1a3530'],
    scratchAccent: '#d4a853',
    fireworkColors: ['#b4914d', '#d4a853', '#e8c66a', '#8b6d2f', '#fff4d0', '#f0d78c', '#ffd700'],
    confettiColors: ['#b4914d', '#d4a853', '#e8c66a', '#22c55e', '#f0d78c', '#fff4d0', '#e8a4b8'],
    doorStyle: {
      type: 'classic-doors',
      doorMaterial: 'wood',
      panelLayout: 'carved',
      handleType: 'ring-knocker',
      frameStyle: 'ornate',
      leftText: 'بِسْمِ اللَّهِ',
      rightText: 'الرَّحْمَنِ الرَّحِيمِ',
      leftTextLang: 'ar',
      rightTextLang: 'ar',
      svgPattern: 'arch',
      centerIcon: '✦',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
  },
  'crimson-royale': {
    id: 'crimson-royale',
    name: 'Crimson Royale',
    bgPrimary: '#1a0a0e',
    bgSecondary: '#120810',
    bgDoor: '#2a1018',
    bgDoorGradient: 'linear-gradient(135deg, #2a1018 0%, #3d1525 50%, #1f0e16 100%)',
    accent: '#dc2626',
    accentLight: '#f87171',
    accentDark: '#991b1b',
    accentRgb: '220,38,38',
    textPrimary: '#f5c6c6',
    textSecondary: '#d4a0a0',
    textMuted: '#8b5e5e',
    borderAccent: 'rgba(220,38,38,0.4)',
    borderSubtle: 'rgba(220,38,38,0.15)',
    scratchBg: ['#2a1018', '#1f0e16', '#3d1525'],
    scratchAccent: '#dc2626',
    fireworkColors: ['#dc2626', '#f87171', '#ef4444', '#b91c1c', '#d4a853', '#ffd700', '#fca5a5'],
    confettiColors: ['#dc2626', '#f87171', '#d4a853', '#ffd700', '#ef4444', '#fca5a5', '#e8c66a'],
    doorStyle: {
      type: 'curtains',
      doorMaterial: 'painted',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'painted-rosettes',
      leftText: 'نّ',
      rightText: 'و',
      leftTextLang: 'ar',
      rightTextLang: 'ar',
      svgPattern: 'floral',
      centerIcon: '👑',
      animationClass: 'door-open',
      buttonStyle: 'shield',
    },
  },
  'majestic-love': {
    id: 'majestic-love',
    name: 'Majestic Love',
    bgPrimary: '#1a1408',
    bgSecondary: '#12100a',
    bgDoor: '#2a2010',
    bgDoorGradient: 'linear-gradient(135deg, #2a2010 0%, #3d3018 50%, #1f1a0e 100%)',
    accent: '#f59e0b',
    accentLight: '#fbbf24',
    accentDark: '#d97706',
    accentRgb: '245,158,11',
    textPrimary: '#f5e6c8',
    textSecondary: '#d4b88a',
    textMuted: '#8b7650',
    borderAccent: 'rgba(245,158,11,0.4)',
    borderSubtle: 'rgba(245,158,11,0.15)',
    scratchBg: ['#2a2010', '#1f1a0e', '#3d3018'],
    scratchAccent: '#f59e0b',
    fireworkColors: ['#f59e0b', '#fbbf24', '#d97706', '#92400e', '#fff4d0', '#fde68a', '#ffd700'],
    confettiColors: ['#f59e0b', '#fbbf24', '#d97706', '#ffd700', '#fde68a', '#fff4d0', '#e8a4b8'],
    doorStyle: {
      type: 'scroll',
      doorMaterial: 'painted',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'simple',
      leftText: 'ع',
      rightText: 'ش',
      leftTextLang: 'ar',
      rightTextLang: 'ar',
      svgPattern: 'paisley',
      centerIcon: '💫',
      animationClass: 'door-open',
      buttonStyle: 'diamond',
    },
  },
  'garden-romance': {
    id: 'garden-romance',
    name: 'Garden Romance',
    bgPrimary: '#1a0a14',
    bgSecondary: '#120810',
    bgDoor: '#2a1020',
    bgDoorGradient: 'linear-gradient(135deg, #2a1020 0%, #3d1830 50%, #1f0e18 100%)',
    accent: '#ec4899',
    accentLight: '#f472b6',
    accentDark: '#be185d',
    accentRgb: '236,72,153',
    textPrimary: '#f5c6e0',
    textSecondary: '#d4a0c0',
    textMuted: '#8b5e78',
    borderAccent: 'rgba(236,72,153,0.4)',
    borderSubtle: 'rgba(236,72,153,0.15)',
    scratchBg: ['#2a1020', '#1f0e18', '#3d1830'],
    scratchAccent: '#ec4899',
    fireworkColors: ['#ec4899', '#f472b6', '#db2777', '#9d174d', '#ffd700', '#fbbf24', '#fca5a5'],
    confettiColors: ['#ec4899', '#f472b6', '#db2777', '#ffd700', '#fbbf24', '#fca5a5', '#e8c66a'],
    doorStyle: {
      type: 'petals',
      doorMaterial: 'painted',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'painted-rosettes',
      leftText: 'Garden',
      rightText: 'Romance',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'floral',
      centerIcon: '🌸',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
  },
  'modern-minimal': {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    bgPrimary: '#0a0e1a',
    bgSecondary: '#080c14',
    bgDoor: '#101828',
    bgDoorGradient: 'linear-gradient(135deg, #101828 0%, #182038 50%, #0e1420 100%)',
    accent: '#60a5fa',
    accentLight: '#93c5fd',
    accentDark: '#3b82f6',
    accentRgb: '96,165,250',
    textPrimary: '#c8daf5',
    textSecondary: '#a0b8d4',
    textMuted: '#5e788b',
    borderAccent: 'rgba(96,165,250,0.4)',
    borderSubtle: 'rgba(96,165,250,0.15)',
    scratchBg: ['#101828', '#0e1420', '#182038'],
    scratchAccent: '#60a5fa',
    fireworkColors: ['#60a5fa', '#93c5fd', '#3b82f6', '#1d4ed8', '#ffd700', '#d4a853', '#dbeafe'],
    confettiColors: ['#60a5fa', '#93c5fd', '#3b82f6', '#ffd700', '#d4a853', '#dbeafe', '#e8c66a'],
    doorStyle: {
      type: 'split-screen',
      doorMaterial: 'glass',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'Save',
      rightText: 'Date',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'minimal',
      centerIcon: '▷',
      animationClass: 'door-open',
      buttonStyle: 'hexagon',
    },
  },
  'mughal-emerald': {
    id: 'mughal-emerald',
    name: 'Mughal Emerald',
    bgPrimary: '#0a1a18',
    bgSecondary: '#081412',
    bgDoor: '#102a25',
    bgDoorGradient: 'linear-gradient(135deg, #102a25 0%, #183d35 50%, #0e2018 100%)',
    accent: '#2dd4bf',
    accentLight: '#5eead4',
    accentDark: '#14b8a6',
    accentRgb: '45,212,191',
    textPrimary: '#c8f5ef',
    textSecondary: '#a0d4c8',
    textMuted: '#5e8b80',
    borderAccent: 'rgba(45,212,191,0.4)',
    borderSubtle: 'rgba(45,212,191,0.15)',
    scratchBg: ['#102a25', '#0e2018', '#183d35'],
    scratchAccent: '#2dd4bf',
    fireworkColors: ['#2dd4bf', '#5eead4', '#14b8a6', '#0d9488', '#ffd700', '#d4a853', '#a7f3d0'],
    confettiColors: ['#2dd4bf', '#5eead4', '#14b8a6', '#ffd700', '#d4a853', '#a7f3d0', '#e8c66a'],
    doorStyle: {
      type: 'archway',
      doorMaterial: 'stone',
      panelLayout: 'carved',
      handleType: 'iron-ring',
      frameStyle: 'arched-stone',
      leftText: 'مغل',
      rightText: 'شاہی',
      leftTextLang: 'ur',
      rightTextLang: 'ur',
      svgPattern: 'mandala',
      centerIcon: '✦',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
  },
  'rose-gold-blush': {
    id: 'rose-gold-blush',
    name: 'Rose Gold Blush',
    isLight: true,
    bgPrimary: '#fff1f2',
    bgSecondary: '#ffffff',
    bgDoor: '#ffe4e6',
    bgDoorGradient: 'linear-gradient(135deg, #ffe4e6 0%, #ffffff 50%, #fecdd3 100%)',
    accent: '#be185d',
    accentLight: '#db2777',
    accentDark: '#9d174d',
    accentRgb: '190,24,93',
    textPrimary: '#881337',
    textSecondary: '#9d174d',
    textMuted: '#db2777',
    borderAccent: 'rgba(190,24,93,0.2)',
    borderSubtle: 'rgba(190,24,93,0.08)',
    scratchBg: ['#fecdd3', '#fda4af', '#fff1f2'],
    scratchAccent: '#be185d',
    fireworkColors: ['#be185d', '#db2777', '#9d174d', '#fda4af', '#fecdd3', '#ffffff'],
    confettiColors: ['#be185d', '#db2777', '#9d174d', '#fda4af', '#fecdd3', '#ffffff'],
    doorStyle: {
      type: 'lotus',
      doorMaterial: 'painted',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'painted-rosettes',
      leftText: 'Rose',
      rightText: 'Gold',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'floral',
      centerIcon: '🌹',
      animationClass: 'door-open',
      buttonStyle: 'diamond',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-calligraphy',
  },
  'ivory-dream': {
    id: 'ivory-dream',
    name: 'Ivory Dream',
    isLight: true,
    bgPrimary: '#fafaf9',
    bgSecondary: '#ffffff',
    bgDoor: '#f5f5f4',
    bgDoorGradient: 'linear-gradient(135deg, #f5f5f4 0%, #ffffff 50%, #e7e5e4 100%)',
    accent: '#78350f',
    accentLight: '#b45309',
    accentDark: '#451a03',
    accentRgb: '120,53,15',
    textPrimary: '#451a03',
    textSecondary: '#78350f',
    textMuted: '#a16207',
    borderAccent: 'rgba(120,53,15,0.25)',
    borderSubtle: 'rgba(120,53,15,0.1)',
    scratchBg: ['#e7e5e4', '#d6d3d1', '#fafaf9'],
    scratchAccent: '#78350f',
    fireworkColors: ['#78350f', '#b45309', '#451a03', '#d6d3d1', '#fafaf9', '#ffffff'],
    confettiColors: ['#78350f', '#b45309', '#451a03', '#d6d3d1', '#fafaf9', '#ffffff'],
    doorStyle: {
      type: 'curtains',
      doorMaterial: 'painted',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'ornate',
      leftText: 'Ivory',
      rightText: 'Dream',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'diamond',
      centerIcon: '◈',
      animationClass: 'door-open',
      buttonStyle: 'diamond',
    },
  },
  'royal-imperial': {
    id: 'royal-imperial',

    name: 'Royal Imperial',
    openingVideoUrl: '/videos/royal-door-open.mp4',
    openingVideoPosterUrl: '/videos/royal-door-poster.webp',
    heroMediaUrl: '/videos/royal-hero-loop.webm',
    bgPrimary: '#160B08',
    bgSecondary: '#1E0F0A',
    bgDoor: '#2a1a10',
    bgDoorGradient: 'linear-gradient(135deg, #2a1a10 0%, #3d2818 50%, #1f140e 100%)',
    accent: '#C9A84C',
    accentLight: '#E8C66A',
    accentDark: '#9A7A32',
    accentRgb: '201,168,76',
    textPrimary: '#F5E6C8',
    textSecondary: '#D4B88A',
    textMuted: '#8B7650',
    borderAccent: 'rgba(201,168,76,0.5)',
    borderSubtle: 'rgba(201,168,76,0.2)',
    scratchBg: ['#2a1a10', '#1f140e', '#3d2818'],
    scratchAccent: '#C9A84C',
    fireworkColors: ['#C9A84C', '#E8C66A', '#9A7A32', '#92400e', '#ffd700', '#fff4d0', '#fde68a', '#e8c66a'],
    confettiColors: ['#C9A84C', '#E8C66A', '#9A7A32', '#ffd700', '#fde68a', '#fff4d0', '#e8a4b8', '#ec4899'],
    doorStyle: {
      type: 'dome',
      doorMaterial: 'stone',
      panelLayout: 'carved',
      handleType: 'none',
      frameStyle: 'ornate',
      leftText: 'سلطنت',
      rightText: 'شاہی',
      leftTextLang: 'ur',
      rightTextLang: 'ur',
      svgPattern: 'dome',
      centerIcon: '👑',
      animationClass: 'door-open',
      buttonStyle: 'shield',
    },
  },
  'royal-elegance': {
    id: 'royal-elegance',
    name: 'Royal Elegance',
    openingVideoUrl: '/videos/royal-elegance-door-open.mp4',
    openingVideoPosterUrl: '/videos/royal-elegance-door-poster.webp',
    heroMediaUrl: '/videos/royal-elegance-hero-loop.mp4',
    bgPrimary: '#0D0008',
    bgSecondary: '#1A0010',
    bgDoor: '#2E0015',
    bgDoorGradient: 'linear-gradient(135deg, #2E0015 0%, #450020 50%, #200010 100%)',
    accent: '#E8305A',
    accentLight: '#FF6B8A',
    accentDark: '#B01840',
    accentRgb: '232,48,90',
    textPrimary: '#F5C6D0',
    textSecondary: '#D4A0B0',
    textMuted: '#8B5E6E',
    borderAccent: 'rgba(232,48,90,0.5)',
    borderSubtle: 'rgba(232,48,90,0.2)',
    scratchBg: ['#2E0015', '#1A0010', '#450020'],
    scratchAccent: '#E8305A',
    fireworkColors: ['#E8305A', '#FF6B8A', '#B01840', '#be123c', '#ffd700', '#d4a853', '#fecdd3', '#e8c66a'],
    confettiColors: ['#E8305A', '#FF6B8A', '#B01840', '#ffd700', '#d4a853', '#fecdd3', '#e8c66a', '#fbbf24'],
    doorStyle: {
      type: 'curtains',
      doorMaterial: 'glass',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'ornate',
      leftText: 'Royal',
      rightText: 'Elegance',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'floral',
      centerIcon: '🌹',
      animationClass: 'door-open',
      buttonStyle: 'diamond',
    },
  },
  'watercolor-peach': {
    id: 'watercolor-peach',
    name: 'Watercolor Peach',
    isLight: true,
    bgPrimary: '#fff7ed',
    bgSecondary: '#ffffff',
    bgDoor: '#ffedd5',
    bgDoorGradient: 'linear-gradient(135deg, #ffedd5 0%, #ffffff 50%, #fed7aa 100%)',
    accent: '#c2410c',
    accentLight: '#ea580c',
    accentDark: '#9a3412',
    accentRgb: '194,65,12',
    textPrimary: '#7c2d12',
    textSecondary: '#9a3412',
    textMuted: '#ea580c',
    borderAccent: 'rgba(194,65,12,0.2)',
    borderSubtle: 'rgba(194,65,12,0.08)',
    scratchBg: ['#ffedd5', '#fed7aa', '#fff7ed'],
    scratchAccent: '#c2410c',
    fireworkColors: ['#c2410c', '#ea580c', '#9a3412', '#ffedd5', '#fed7aa', '#ffffff'],
    confettiColors: ['#c2410c', '#ea580c', '#9a3412', '#ffedd5', '#fed7aa', '#ffffff'],
    doorStyle: {
      type: 'petals',
      doorMaterial: 'painted',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'painted-rosettes',
      leftText: 'Watercolor',
      rightText: 'Peach',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'floral',
      centerIcon: '🍑',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-calligraphy',
  },
  'geometric-gold': {
    id: 'geometric-gold',
    name: 'Geometric Gold',
    openingVideoUrl: '/videos/geometric-gold-door-open.mp4',
    openingVideoPosterUrl: '/videos/geometric-gold-door-poster.webp',
    heroMediaUrl: '/videos/geometric-gold-hero-loop.mp4',
    bgPrimary: '#080C18',
    bgSecondary: '#0E1525',
    bgDoor: '#1A2540',
    bgDoorGradient: 'linear-gradient(135deg, #1A2540 0%, #243060 50%, #101830 100%)',
    accent: '#F5C842',
    accentLight: '#FFE066',
    accentDark: '#B8920A',
    accentRgb: '245,200,66',
    textPrimary: '#FEFCE8',
    textSecondary: '#FDE68A',
    textMuted: '#78716C',
    borderAccent: 'rgba(245,200,66,0.5)',
    borderSubtle: 'rgba(245,200,66,0.2)',
    scratchBg: ['#1A2540', '#0E1525', '#243060'],
    scratchAccent: '#F5C842',
    fireworkColors: ['#F5C842', '#FFE066', '#B8920A', '#d97706', '#ffd700', '#fff4d0', '#fde68a'],
    confettiColors: ['#F5C842', '#FFE066', '#B8920A', '#ffd700', '#fff4d0', '#fde68a', '#e8c66a'],
    doorStyle: {
      type: 'geometric',
      doorMaterial: 'glass',
      panelLayout: 'glass-grid',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'Geometric',
      rightText: 'Gold',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'geometric',
      centerIcon: '⬡',
      animationClass: 'door-open',
      buttonStyle: 'hexagon',
    },
  },
  'dark-velvet': {
    id: 'dark-velvet',
    name: 'Dark Velvet',
    openingVideoUrl: '/videos/dark-velvet-door-open.mp4',
    openingVideoPosterUrl: '/videos/dark-velvet-door-poster.webp',
    heroMediaUrl: '/videos/dark-velvet-hero-loop.mp4',
    bgPrimary: '#04010F',
    bgSecondary: '#0A0520',
    bgDoor: '#120A30',
    bgDoorGradient: 'linear-gradient(135deg, #120A30 0%, #1E1050 50%, #0A0520 100%)',
    accent: '#9B5FE0',
    accentLight: '#C084FC',
    accentDark: '#6B21A8',
    accentRgb: '155,95,224',
    textPrimary: '#DDD6FE',
    textSecondary: '#C4B5FD',
    textMuted: '#4C1D95',
    borderAccent: 'rgba(155,95,224,0.5)',
    borderSubtle: 'rgba(155,95,224,0.2)',
    scratchBg: ['#120A30', '#0A0520', '#1E1050'],
    scratchAccent: '#9B5FE0',
    fireworkColors: ['#9B5FE0', '#C084FC', '#6B21A8', '#7c3aed', '#ffd700', '#d8b4fe', '#f3e8ff'],
    confettiColors: ['#9B5FE0', '#C084FC', '#6B21A8', '#ffd700', '#d8b4fe', '#f3e8ff', '#e8c66a'],
    doorStyle: {
      type: 'classic-doors',
      doorMaterial: 'painted',
      panelLayout: 'flat',
      handleType: 'ring-knocker',
      frameStyle: 'simple',
      leftText: 'Dark',
      rightText: 'Velvet',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'diamond',
      centerIcon: '✦',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
  },
  'pastel-floral': {
    id: 'pastel-floral',
    name: 'Pastel Floral',
    isLight: true,
    bgPrimary: '#fdf2f8',
    bgSecondary: '#ffffff',
    bgDoor: '#fbcfe8',
    bgDoorGradient: 'linear-gradient(135deg, #fbcfe8 0%, #ffffff 50%, #f9a8d4 100%)',
    accent: '#be185d',
    accentLight: '#db2777',
    accentDark: '#9d174d',
    accentRgb: '190,24,93',
    textPrimary: '#831843',
    textSecondary: '#9d174d',
    textMuted: '#db2777',
    borderAccent: 'rgba(190,24,93,0.2)',
    borderSubtle: 'rgba(190,24,93,0.08)',
    scratchBg: ['#fbcfe8', '#f9a8d4', '#fdf2f8'],
    scratchAccent: '#be185d',
    fireworkColors: ['#be185d', '#db2777', '#9d174d', '#fbcfe8', '#f9a8d4', '#ffffff'],
    confettiColors: ['#be185d', '#db2777', '#9d174d', '#fbcfe8', '#f9a8d4', '#ffffff'],
    doorStyle: {
      type: 'curtains',
      doorMaterial: 'painted',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'painted-rosettes',
      leftText: 'Pastel',
      rightText: 'Floral',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'floral',
      centerIcon: '🌸',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-calligraphy',
  },
  'minimal-white': {
    id: 'minimal-white',
    name: 'Minimal White',
    isLight: true,
    bgPrimary: '#f8fafc',
    bgSecondary: '#ffffff',
    bgDoor: '#f1f5f9',
    bgDoorGradient: 'linear-gradient(135deg, #e2e8f0 0%, #ffffff 50%, #cbd5e1 100%)',
    accent: '#0f172a',
    accentLight: '#475569',
    accentDark: '#020617',
    accentRgb: '15,23,42',
    textPrimary: '#0f172a',
    textSecondary: '#334155',
    textMuted: '#64748b',
    borderAccent: 'rgba(15,23,42,0.15)',
    borderSubtle: 'rgba(15,23,42,0.06)',
    scratchBg: ['#0f172a', '#1e293b', '#334155'],
    scratchAccent: '#ffffff',
    fireworkColors: ['#0f172a', '#334155', '#475569', '#64748b', '#cbd5e1', '#ffffff'],
    confettiColors: ['#0f172a', '#334155', '#475569', '#cbd5e1', '#ffffff'],
    doorStyle: {
      type: 'split-screen',
      doorMaterial: 'glass',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'Save',
      rightText: 'Date',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'minimal',
      centerIcon: '💍',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-sans',
  },
  // ==================== BIRTHDAY CLASSICS ====================
  'pastel-paradise': {
    id: 'pastel-paradise',
    name: 'Pastel Paradise',
    isLight: true,
    bgPrimary: '#fcf8ff',
    bgSecondary: '#f5e8fc',
    bgDoor: '#fae8ff',
    bgDoorGradient: 'linear-gradient(135deg, #fdf4ff 0%, #fae8ff 50%, #f0abfc 100%)',
    accent: '#c026d3',
    accentLight: '#e879f9',
    accentDark: '#86198f',
    accentRgb: '192,38,211',
    textPrimary: '#3b0764',
    textSecondary: '#701a75',
    textMuted: '#a21caf',
    borderAccent: 'rgba(192,38,211,0.25)',
    borderSubtle: 'rgba(192,38,211,0.1)',
    scratchBg: ['#fae8ff', '#f5d0fe', '#e879f9'],
    scratchAccent: '#c026d3',
    fireworkColors: ['#f472b6', '#c026d3', '#38bdf8', '#fbbf24', '#ffffff'],
    confettiColors: ['#f472b6', '#c026d3', '#38bdf8', '#fbbf24', '#ffffff'],
    doorStyle: {
      type: 'curtains',
      doorMaterial: 'painted',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'Happy',
      rightText: 'Birthday',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'star',
      centerIcon: '🎂',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-sans',
  },
  'boho-chic': {
    id: 'boho-chic',
    name: 'Boho Chic',
    isLight: true,
    bgPrimary: '#faf5ef',
    bgSecondary: '#f4eae0',
    bgDoor: '#eeddcc',
    bgDoorGradient: 'linear-gradient(135deg, #fdfbf7 0%, #f4eae0 50%, #d4a373 100%)',
    accent: '#b05d3b',
    accentLight: '#cb7d5d',
    accentDark: '#8c3e21',
    accentRgb: '176,93,59',
    textPrimary: '#3d2518',
    textSecondary: '#6a432d',
    textMuted: '#966e54',
    borderAccent: 'rgba(176,93,59,0.25)',
    borderSubtle: 'rgba(176,93,59,0.1)',
    scratchBg: ['#faede1', '#f3d5b5', '#d4a373'],
    scratchAccent: '#b05d3b',
    fireworkColors: ['#b05d3b', '#d4a373', '#e9edc9', '#ccd5ae', '#ffffff'],
    confettiColors: ['#b05d3b', '#d4a373', '#faedcd', '#ffffff'],
    doorStyle: {
      type: 'archway',
      doorMaterial: 'wood',
      panelLayout: 'arched-panel',
      handleType: 'ring-knocker',
      frameStyle: 'arched-stone',
      leftText: 'Celebrate',
      rightText: 'Life',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'floral',
      centerIcon: '✨',
      animationClass: 'door-open',
      buttonStyle: 'diamond',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-serif',
  },
  'vintage-milestones': {
    id: 'vintage-milestones',
    name: 'Vintage Milestones',
    isLight: false,
    bgPrimary: '#111114',
    bgSecondary: '#1a1a20',
    bgDoor: '#16161c',
    bgDoorGradient: 'linear-gradient(135deg, #1f1f27 0%, #16161c 50%, #0d0d10 100%)',
    accent: '#d4af37',
    accentLight: '#f3e5ab',
    accentDark: '#aa820a',
    accentRgb: '212,175,55',
    textPrimary: '#fcfcfc',
    textSecondary: '#d6d6db',
    textMuted: '#8c8c96',
    borderAccent: 'rgba(212,175,55,0.35)',
    borderSubtle: 'rgba(212,175,55,0.15)',
    scratchBg: ['#22222b', '#2e2e3a', '#18181f'],
    scratchAccent: '#d4af37',
    fireworkColors: ['#d4af37', '#f3e5ab', '#ffffff', '#e5c158', '#997510'],
    confettiColors: ['#d4af37', '#f3e5ab', '#ffffff', '#e5c158'],
    doorStyle: {
      type: 'classic-doors',
      doorMaterial: 'lacquer',
      panelLayout: '4-panel',
      handleType: 'lever',
      frameStyle: 'ornate',
      leftText: 'Vintage',
      rightText: 'Milestone',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'geometric',
      centerIcon: '👑',
      animationClass: 'door-open',
      buttonStyle: 'shield',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-serif',
  },

  // ==================== SCHOOL & COLLEGE CLASSICS ====================
  'academic-excellence': {
    id: 'academic-excellence',
    name: 'Academic Excellence',
    isLight: false,
    bgPrimary: '#091326',
    bgSecondary: '#0d1d3a',
    bgDoor: '#0b1833',
    bgDoorGradient: 'linear-gradient(135deg, #11264e 0%, #0b1833 50%, #060e1d 100%)',
    accent: '#f59e0b',
    accentLight: '#fcd34d',
    accentDark: '#b45309',
    accentRgb: '245,158,11',
    textPrimary: '#ffffff',
    textSecondary: '#cbd5e1',
    textMuted: '#94a3b8',
    borderAccent: 'rgba(245,158,11,0.35)',
    borderSubtle: 'rgba(245,158,11,0.15)',
    scratchBg: ['#0d1d3a', '#1e293b', '#091326'],
    scratchAccent: '#f59e0b',
    fireworkColors: ['#f59e0b', '#38bdf8', '#ffffff', '#fbbf24'],
    confettiColors: ['#f59e0b', '#38bdf8', '#ffffff', '#fbbf24'],
    doorStyle: {
      type: 'classic-doors',
      doorMaterial: 'wood',
      panelLayout: '2-panel',
      handleType: 'ring-knocker',
      frameStyle: 'ornate',
      leftText: 'Class of',
      rightText: '2027',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'geometric',
      centerIcon: '🎓',
      animationClass: 'door-open',
      buttonStyle: 'shield',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-serif',
  },
  'future-innovators': {
    id: 'future-innovators',
    name: 'Future Innovators',
    isLight: false,
    bgPrimary: '#080d16',
    bgSecondary: '#0f1726',
    bgDoor: '#0b121f',
    bgDoorGradient: 'linear-gradient(135deg, #16243b 0%, #0b121f 50%, #05080f 100%)',
    accent: '#06b6d4',
    accentLight: '#67e8f9',
    accentDark: '#0891b2',
    accentRgb: '6,182,212',
    textPrimary: '#f8fafc',
    textSecondary: '#94a3b8',
    textMuted: '#64748b',
    borderAccent: 'rgba(6,182,212,0.35)',
    borderSubtle: 'rgba(6,182,212,0.12)',
    scratchBg: ['#0f1726', '#1e293b', '#080d16'],
    scratchAccent: '#06b6d4',
    fireworkColors: ['#06b6d4', '#3b82f6', '#10b981', '#ffffff'],
    confettiColors: ['#06b6d4', '#3b82f6', '#10b981', '#ffffff'],
    doorStyle: {
      type: 'split-screen',
      doorMaterial: 'glass',
      panelLayout: 'glass-grid',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'Hack',
      rightText: 'Innovate',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'minimal',
      centerIcon: '⚡',
      animationClass: 'door-open',
      buttonStyle: 'hexagon',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-sans',
  },
  'campus-memories': {
    id: 'campus-memories',
    name: 'Campus Memories',
    isLight: true,
    bgPrimary: '#fcfaf6',
    bgSecondary: '#f5ede1',
    bgDoor: '#eedecb',
    bgDoorGradient: 'linear-gradient(135deg, #fdfbf9 0%, #eedecb 50%, #ddc4a8 100%)',
    accent: '#991b1b',
    accentLight: '#dc2626',
    accentDark: '#7f1d1d',
    accentRgb: '153,27,27',
    textPrimary: '#2e1212',
    textSecondary: '#5c2a2a',
    textMuted: '#8a4e4e',
    borderAccent: 'rgba(153,27,27,0.25)',
    borderSubtle: 'rgba(153,27,27,0.1)',
    scratchBg: ['#fdf4ea', '#f5ede1', '#ebd4bd'],
    scratchAccent: '#991b1b',
    fireworkColors: ['#991b1b', '#f59e0b', '#dc2626', '#ffffff'],
    confettiColors: ['#991b1b', '#f59e0b', '#eedecb', '#ffffff'],
    doorStyle: {
      type: 'archway',
      doorMaterial: 'wood',
      panelLayout: 'arched-panel',
      handleType: 'ring-knocker',
      frameStyle: 'arched-stone',
      leftText: 'Farewell',
      rightText: 'Reunion',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'floral',
      centerIcon: '📚',
      animationClass: 'door-open',
      buttonStyle: 'diamond',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-serif',
  },

  // ==================== MEETINGS & CORPORATE CLASSICS ====================
  'executive-summit': {
    id: 'executive-summit',
    name: 'Executive Summit',
    isLight: false,
    bgPrimary: '#0b111e',
    bgSecondary: '#121b2d',
    bgDoor: '#0e1626',
    bgDoorGradient: 'linear-gradient(135deg, #18253e 0%, #0e1626 50%, #070a12 100%)',
    accent: '#38bdf8',
    accentLight: '#7dd3fc',
    accentDark: '#0284c7',
    accentRgb: '56,189,248',
    textPrimary: '#ffffff',
    textSecondary: '#94a3b8',
    textMuted: '#64748b',
    borderAccent: 'rgba(56,189,248,0.3)',
    borderSubtle: 'rgba(56,189,248,0.12)',
    scratchBg: ['#121b2d', '#1e293b', '#0b111e'],
    scratchAccent: '#38bdf8',
    fireworkColors: ['#38bdf8', '#0284c7', '#ffffff', '#64748b'],
    confettiColors: ['#38bdf8', '#0284c7', '#ffffff'],
    doorStyle: {
      type: 'split-screen',
      doorMaterial: 'glass',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'Annual',
      rightText: 'Summit',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'minimal',
      centerIcon: '💼',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-sans',
  },
  'creative-startup': {
    id: 'creative-startup',
    name: 'Creative Startup',
    isLight: false,
    bgPrimary: '#0a0a0c',
    bgSecondary: '#141418',
    bgDoor: '#101014',
    bgDoorGradient: 'linear-gradient(135deg, #1c1c22 0%, #101014 50%, #060608 100%)',
    accent: '#f97316',
    accentLight: '#fb923c',
    accentDark: '#ea580c',
    accentRgb: '249,115,22',
    textPrimary: '#ffffff',
    textSecondary: '#a1a1aa',
    textMuted: '#71717a',
    borderAccent: 'rgba(249,115,22,0.35)',
    borderSubtle: 'rgba(249,115,22,0.12)',
    scratchBg: ['#141418', '#27272a', '#0a0a0c'],
    scratchAccent: '#f97316',
    fireworkColors: ['#f97316', '#fbbf24', '#ffffff', '#ef4444'],
    confettiColors: ['#f97316', '#fbbf24', '#ffffff'],
    doorStyle: {
      type: 'split-screen',
      doorMaterial: 'glass',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'NextGen',
      rightText: 'Launch',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'geometric',
      centerIcon: '🚀',
      animationClass: 'door-open',
      buttonStyle: 'hexagon',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-sans',
  },
  'global-connect': {
    id: 'global-connect',
    name: 'Global Connect',
    isLight: false,
    bgPrimary: '#061311',
    bgSecondary: '#0b211e',
    bgDoor: '#091a18',
    bgDoorGradient: 'linear-gradient(135deg, #11312d 0%, #091a18 50%, #040d0c 100%)',
    accent: '#10b981',
    accentLight: '#34d399',
    accentDark: '#059669',
    accentRgb: '16,185,129',
    textPrimary: '#ffffff',
    textSecondary: '#a7f3d0',
    textMuted: '#6ee7b7',
    borderAccent: 'rgba(16,185,129,0.35)',
    borderSubtle: 'rgba(16,185,129,0.12)',
    scratchBg: ['#0b211e', '#134e4a', '#061311'],
    scratchAccent: '#10b981',
    fireworkColors: ['#10b981', '#34d399', '#38bdf8', '#ffffff'],
    confettiColors: ['#10b981', '#34d399', '#ffffff'],
    doorStyle: {
      type: 'geometric',
      doorMaterial: 'glass',
      panelLayout: 'glass-grid',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'Global',
      rightText: 'Connect',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'geometric',
      centerIcon: '🌐',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-sans',
  },
  // ==================== NEW ROYAL THEMES ====================
  'golden-jubilee': {
    id: 'golden-jubilee',
    name: 'Golden Jubilee (VIP Birthday)',
    isLight: false,
    bgPrimary: '#120f06',
    bgSecondary: '#1f190a',
    bgDoor: '#1a1408',
    bgDoorGradient: 'linear-gradient(135deg, #2b220d 0%, #1a1408 50%, #0d0a04 100%)',
    accent: '#fbbf24',
    accentLight: '#fde68a',
    accentDark: '#d97706',
    accentRgb: '251,191,36',
    textPrimary: '#fffbeb',
    textSecondary: '#fef3c7',
    textMuted: '#d97706',
    borderAccent: 'rgba(251,191,36,0.35)',
    borderSubtle: 'rgba(251,191,36,0.12)',
    scratchBg: ['#1f190a', '#2b220d', '#120f06'],
    scratchAccent: '#fbbf24',
    fireworkColors: ['#fbbf24', '#f59e0b', '#ffffff', '#fde68a'],
    confettiColors: ['#fbbf24', '#f59e0b', '#ffffff', '#fde68a'],
    doorStyle: {
      type: 'classic-doors',
      doorMaterial: 'lacquer',
      panelLayout: '4-panel',
      handleType: 'ring-knocker',
      frameStyle: 'ornate',
      leftText: 'Golden',
      rightText: 'Jubilee',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'geometric',
      centerIcon: '👑',
      animationClass: 'door-open',
      buttonStyle: 'shield',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-serif',
  },
  'grand-gala': {
    id: 'grand-gala',
    name: 'The Grand Gala (School & Prom)',
    isLight: false,
    bgPrimary: '#0f050e',
    bgSecondary: '#1f0d1d',
    bgDoor: '#180816',
    bgDoorGradient: 'linear-gradient(135deg, #2e102a 0%, #180816 50%, #0d040c 100%)',
    accent: '#f43f5e',
    accentLight: '#fda4af',
    accentDark: '#be123c',
    accentRgb: '244,63,94',
    textPrimary: '#fff1f2',
    textSecondary: '#fecdd3',
    textMuted: '#fb7185',
    borderAccent: 'rgba(244,63,94,0.35)',
    borderSubtle: 'rgba(244,63,94,0.12)',
    scratchBg: ['#1f0d1d', '#2e102a', '#0f050e'],
    scratchAccent: '#f43f5e',
    fireworkColors: ['#f43f5e', '#fb7185', '#ffffff', '#e11d48'],
    confettiColors: ['#f43f5e', '#fb7185', '#ffffff', '#fda4af'],
    doorStyle: {
      type: 'curtains',
      doorMaterial: 'painted',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'ornate',
      leftText: 'Grand',
      rightText: 'Gala',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'star',
      centerIcon: '✨',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-serif',
  },
  'valedictorian-prestige': {
    id: 'valedictorian-prestige',
    name: 'Valedictorian Prestige (Graduation)',
    isLight: false,
    bgPrimary: '#04140e',
    bgSecondary: '#0a231b',
    bgDoor: '#071c15',
    bgDoorGradient: 'linear-gradient(135deg, #10382b 0%, #071c15 50%, #020b08 100%)',
    accent: '#10b981',
    accentLight: '#6ee7b7',
    accentDark: '#047857',
    accentRgb: '16,185,129',
    textPrimary: '#ecfdf5',
    textSecondary: '#a7f3d0',
    textMuted: '#34d399',
    borderAccent: 'rgba(16,185,129,0.35)',
    borderSubtle: 'rgba(16,185,129,0.12)',
    scratchBg: ['#0a231b', '#10382b', '#04140e'],
    scratchAccent: '#10b981',
    fireworkColors: ['#10b981', '#fbbf24', '#ffffff', '#34d399'],
    confettiColors: ['#10b981', '#fbbf24', '#ffffff', '#6ee7b7'],
    doorStyle: {
      type: 'classic-doors',
      doorMaterial: 'wood',
      panelLayout: 'arched-panel',
      handleType: 'ring-knocker',
      frameStyle: 'ornate',
      leftText: 'Class of',
      rightText: 'Honors',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'geometric',
      centerIcon: '🎓',
      animationClass: 'door-open',
      buttonStyle: 'shield',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-serif',
  },
  'the-boardroom': {
    id: 'the-boardroom',
    name: 'The Boardroom (Corporate Executive)',
    isLight: false,
    bgPrimary: '#0f0f12',
    bgSecondary: '#18181d',
    bgDoor: '#141418',
    bgDoorGradient: 'linear-gradient(135deg, #24242c 0%, #141418 50%, #08080a 100%)',
    accent: '#f59e0b',
    accentLight: '#fbbf24',
    accentDark: '#b45309',
    accentRgb: '245,158,11',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
    textMuted: '#94a3b8',
    borderAccent: 'rgba(245,158,11,0.35)',
    borderSubtle: 'rgba(245,158,11,0.12)',
    scratchBg: ['#18181d', '#24242c', '#0f0f12'],
    scratchAccent: '#f59e0b',
    fireworkColors: ['#f59e0b', '#fbbf24', '#ffffff', '#94a3b8'],
    confettiColors: ['#f59e0b', '#fbbf24', '#ffffff'],
    doorStyle: {
      type: 'split-screen',
      doorMaterial: 'glass',
      panelLayout: 'glass-grid',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'Executive',
      rightText: 'Boardroom',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'minimal',
      centerIcon: '🏢',
      animationClass: 'door-open',
      buttonStyle: 'circle',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-sans',
  },
  'visionary-keynote': {
    id: 'visionary-keynote',
    name: 'Visionary Keynote (Tech Launch)',
    isLight: false,
    bgPrimary: '#030712',
    bgSecondary: '#0a1024',
    bgDoor: '#060c1d',
    bgDoorGradient: 'linear-gradient(135deg, #101c3d 0%, #060c1d 50%, #02040a 100%)',
    accent: '#38bdf8',
    accentLight: '#7dd3fc',
    accentDark: '#0284c7',
    accentRgb: '56,189,248',
    textPrimary: '#f8fafc',
    textSecondary: '#94a3b8',
    textMuted: '#64748b',
    borderAccent: 'rgba(56,189,248,0.35)',
    borderSubtle: 'rgba(56,189,248,0.12)',
    scratchBg: ['#0a1024', '#101c3d', '#030712'],
    scratchAccent: '#38bdf8',
    fireworkColors: ['#38bdf8', '#818cf8', '#ffffff', '#3b82f6'],
    confettiColors: ['#38bdf8', '#818cf8', '#ffffff'],
    doorStyle: {
      type: 'split-screen',
      doorMaterial: 'glass',
      panelLayout: 'flat',
      handleType: 'none',
      frameStyle: 'modern',
      leftText: 'Visionary',
      rightText: 'Keynote',
      leftTextLang: 'en',
      rightTextLang: 'en',
      svgPattern: 'minimal',
      centerIcon: '⚡',
      animationClass: 'door-open',
      buttonStyle: 'hexagon',
    },
    fontDisplay: 'font-display',
    fontCalligraphy: 'font-sans',
  },
}

export const DEFAULT_THEME = TEMPLATE_THEMES['emerald-noir']



